name: cofe_fest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  http: ^1.1.0
  equatable: ^2.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  video_player: ^2.9.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  connectivity_plus: ^3.0.3
  yandex_mapkit: ^3.3.3

  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/cofefest.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/gif/
