name: lab_1_menu
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  video_player: ^2.9.1

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/src/assets/icon/cofefest.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/classic_1.jpg
    - assets/images/classic_2.jpg
    - assets/images/classic_3.jpg
    - assets/images/classic_4.jpg
    - assets/images/classic_5.jpg
    - assets/images/classic_6.jpg
    - assets/images/classic_7.jpg
    - assets/images/classic_8.jpg
    - assets/images/autor_1.jpg
    - assets/images/autor_2.jpg
    - assets/images/autor_3.jpg
    - assets/images/autor_4.jpg
    - assets/images/autor_5.jpg
    - assets/images/autor_6.jpg
    - assets/images/autor_7.jpg
    - assets/images/autor_8.jpg
    - assets/images/season_1.jpg
    - assets/images/season_2.jpg
    - assets/images/season_3.jpg
    - assets/images/season_4.jpg
    - assets/images/season_5.jpg
    - assets/images/season_6.jpg
    - assets/images/hot_1.jpg
    - assets/images/hot_2.jpg
    - assets/images/hot_3.jpg
    - assets/images/hot_4.jpg
    - assets/images/hot_5.jpg
    - assets/images/hot_6.jpg
    - assets/images/hot_7.jpg
    - assets/images/hot_8.jpg
    - assets/images/fresh_1.jpg
    - assets/images/fresh_2.jpg
    - assets/images/fresh_3.jpg
    - assets/video/Cofe-Fest.gif
